smembrane_cut_of.pu

@startuml
title membrane cut of sequence

participant ground_station
participant COBC_OBC
participant MDC_PIC
participant RPI

activate COBC_OBC

== start membrane cut of sequence ==
ground_station -> COBC_OBC      : uplink the command
COBC_OBC -> ground_station      : downlink the response command

== IMU function check ==
COBC_OBC -> MDC_PIC             : MDC POWER ON command
activate MDC_PIC
MDC_PIC -> COBC_OBC             : ack
COBC_OBC -> MDC_PIC             : IMU measure check command
hnote over MDC_PIC              : sync with OBC
rnote left of MDC_PIC           : start IMU measuring
rnote left of MDC_PIC           : end IMU measuring
MDC_PIC -> COBC_OBC             : send IMU data
COBC_OBC -> ground_station      : downlink the IMU data
note over ground_station        : check the status of IMU data
COBC_OBC -> MDC_PIC             : MDC POWER OFF command
deactivate MDC_PIC

== uplink the melting the gut command ==
ground_station -> COBC_OBC      : uplink the command
COBC_OBC -> ground_station      : downlink the response command

== melting the gut ==
COBC_OBC -> MDC_PIC             : MDC POWER ON command
activate MDC_PIC
COBC_OBC -> RPI                 : RPI POWER ON command
activate RPI
COBC_OBC -> MDC_PIC             : melting the gut command
COBC_OBC -> RPI                 : melting the gut command
hnote over MDC_PIC, RPI         : sync with OBC
rnote left of MDC_PIC           : start IMU measuring
rnote right of RPI              : melting the gut
rnote left of MDC_PIC           : end IMU measuring
MDC_PIC -> COBC_OBC             : send IMU data
COBC_OBC -> ground_station      : downlink the IMU data
note over ground_station        : check the status of IMU data
COBC_OBC -> RPI                 : RPI POWER OFF command
deactivate RPI
COBC_OBC -> MDC_PIC             : MDC POWER OFF command
deactivate MDC_PIC

== uplink the cut of mast command ==
ground_station -> COBC_OBC      : uplink the command
COBC_OBC -> ground_station      : downlink the response command

== cut of the mast ==
COBC_OBC -> MDC_PIC             : MDC POWER ON command
activate MDC_PIC
COBC_OBC -> RPI                 : RPI POWER ON command
activate RPI
COBC_OBC -> MDC_PIC             : cut of the mast command
COBC_OBC -> RPI                 : cut of the mast command
hnote over MDC_PIC, RPI         : sync with OBC
rnote left of MDC_PIC           : start IMU measuring
rnote right of RPI              : start mast extension
rnote right of RPI              : check the encode data
hnote over MDC_PIC, RPI         : wait cutting of the mast
hnote over MDC_PIC, RPI         : finish cutting of the mast
RPI -> COBC_OBC                 : send encode data
COBC_OBC -> RPI                 : RPI POWER OFF command
deactivate RPI
COBC_OBC -> MDC_PIC             : MDC POWER OFF command
deactivate MDC_PIC
MDC_PIC -> COBC_OBC             : send IMU data
COBC_OBC -> ground_station      : downlink the data of encode and IMU
note over ground_station        : check the status of the data of encode and IMU

== uplink the camera check command ==
ground_station -> COBC_OBC      : uplink the command
COBC_OBC -> ground_station      : downlink the response command

== check by camera ==
COBC_OBC -> RPI                 : RPI POWER ON command
activate RPI
COBC_OBC -> RPI                 : check by camera command
hnote over RPI                  : sync with OBC
rnote right of RPI              : LED ON
rnote right of RPI              : take the phote with sutereo camera
rnote right of RPI              : resize the phote data
rnote right of RPI              : LED OFF
RPI -> COBC_OBC                 : send photo data
COBC_OBC -> RPI                 : RPI POWER OFF command
deactivate RPI
COBC_OBC -> ground_station      : downlink the photo data
note over ground_station        : check that cut off mast sequence is success or not


