@startuml
title mast extension sequence

participant GS
participant 5R8G
participant RX_COBC
participant TX_COBC
database EEPROM
participant OBC
participant RPI
participant MDC

activate RX_COBC
activate TX_COBC
activate OBC
==start mast extension sequence==
GS -> OBC           : Uplink The Command
OBC --> GS          : Downlink The Command Response
==IMU function check==
RX_COBC -> RX_COBC  : Check The Mode
opt power shortage
    TX_COBC -> GS   : Downlink The Power Value
    note over GS    : Return start mast extension sequence
end

OBC -> MDC          : Turn On MDC
activate MDC
OBC -> MDC          : Synchronize Time
OBC -> MDC          : Transfer Measure IMU Command
OBC -> TX_COBC      : Transfer Measure IMU Command
OBC -> MDC          : Transfer Send IMU Data Command
MDC --> OBC         : Send IMU Data
TX_COBC -> EEPROM   : Save IMU Data
OBC -> MDC          : Turn Off MDC
deactivate MDC
OBC -> GS           : Downlink The IMU Data
GS  -> GS           : Check the status of IMU data
opt IMU data are unexpected value
    note over GS    : Return start mast extension sequence
end

==uplink synchronize time and unlock HRM command==
GS -> OBC           : Uplink The Command
OBC --> GS          : Downlink The Command Response

==time sync and unlock HRM==
RX_COBC -> RX_COBC  : Check The Mode
opt power shortage
    TX_COBC -> GS   : Downlink The Power Value
    note over GS    : Return start mast extension sequence
end

OBC -> MDC          : Turn On MDC
activate MDC
OBC -> RPI          : Turn On RPI
activate RPI
RPI --> OBC         : Regular Telemetry
OBC -> RPI          : Transfer RUN Mode Command
OBC -> MDC          : Synchronize Time
OBC -> RPI          : Synchronize Time
OBC -> MDC          : Transfer Measure IMU Command
OBC -> TX_COBC      : Transfer Measure IMU Command
OBC -> RPI          : Transfser Start Melting The Gut Command
OBC -> RPI          : Transfer Stop Melting The Gut Command
OBC -> RPI          : Turn Off RPI
deactivate RPI

OBC -> MDC          : Transfer Send IMU Data Command
MDC --> OBC         : Send IMU Data
TX_COBC -> EEPROM   : Save IMU Data
OBC -> MDC          : Turn Off MDC
deactivate MDC

OBC -> OBC          : Get Max Value of IMU (MDC)
OBC -> OBC          : Get Max Value of IMU (TX_COBC)
OBC -> GS           : Downlink The IMU Data (UHF)

opt HRM locked
    note over GS    : Return command uplink phase
end

==uplink mast extension command==
GS -> OBC   : Uplink The Command
OBC --> GS   : Downlink The Command Response

==mast extension==
OBC -> MDC          : Turn On MDC
activate MDC
OBC -> RPI          : Turn On RPI
activate RPI
RPI --> OBC         : Regular Telemetry

OBC -> MDC          : Synchronize Time
OBC -> RPI          : Synchronize Time
loop time < specified time
    OBC -> OBC      : Check the time
end

RX_COBC -> RX_COBC  : Check The Mode
opt power shortage
    RX_COBC -> GS   : Downlink The Power Value
    note over GS    : Return start mast extension sequence
end

OBC -> MDC          : Transfer Measure IMU Command
OBC -> RX_COBC      : Transfer Measure IMU Command
OBC -> OBC          : Turn On EPS SW1(Motor)
OBC -> RPI          : Transfer Start Mast Extension Command
loop mast extension time < TBD[s]
    OBC -> OBC      : Get Current And Encoder Value
    opt Current or Encoder Value is unexpected
        OBC -> RPI  : Turn Off RPI
        OBC -> OBC  : Turn Off EPS SW1(Motor)
        OBC -> MDC  : Turn Off MDC
        OBC -> GS   : Downlink Encoder Value
        note over GS    : Return command uplink phase
    end
end

OBC -> RPI          : Transfer Stop Mast Extension Command
OBC -> OBC          : Turn Off EPS SW1(Motor)
OBC -> OBC          : Get Encoder Value
OBC -> RPI          : Turn Off RPI
deactivate RPI
OBC -> MDC          : Transfer Send IMU Data Command
MDC --> OBC         : Send IMU Data
OBC -> MDC          : Turn Off MDC
TX_COBC -> EEPROM   : Save IMU Data
deactivate MDC

OBC -> OBC          : Get Max Value of IMU (MDC)
OBC -> OBC          : Get Max Value of IMU (TX_COBC)

OBC -> GS   : Downlink The IMU And Encoder Data
opt IMU and endoder data are unexpected
    note over GS    : Return command uplink phase
end

opt Taking pictures is not implemented
    alt Extension length > 1[m]
        note over GS    : Finish mast extension sequence
    else Extension length < 1[m]
        note over GS    : Return command uplink phase
    end
end

==uplink take pictures command==
GS -> OBC           : Uplink The Command
OBC --> GS          : Downlink The Command Response

==take pictures with stereo camera==
GS -> OBC           : Synchronize Time
loop time < specified time
    OBC -> OBC      : Check the time
end

RX_COBC -> RX_COBC  : Check The Mode
opt power shortage
    TX_COBC -> GS   : Downlink The Power Value
    note over GS    : Return start mast extension sequence
end

OBC -> RPI          : Turn On RPI(EPS SW5)
activate RPI
RPI --> OBC         : Regular Telemetry
OBC -> RPI          : Transfer RUN Mode Command
OBC -> OBC          : Turn On EPS SW6(LED)
OBC -> RPI          : Transfer Turn On LED Command
OBC -> RPI          : Transfer Take A Picture Command (stereo camera)
OBC -> RPI          : Transfer Resize Image
OBC -> RPI          : Transfer Turn Off LED Command
OBC -> RPI          : Transfer Send Image Data Command
RPI --> OBC         : Send Image Data (original and resized)
OBC -> OBC          : Turn Off EPS SW6(LED)
OBC -> RPI          : RPI POWER OFF Command

deactivate RPI
OBC -> GS           : Downlink The Tmage Data
alt Extension length > 1[m]
    note over GS    : Finish mast extension sequence
else Extension length < 1[m]
    note over GS    : Return mast extension command uplink phase
end

@enduml